### ISSUE TITLE
bash demo.sh failed

### ISSUE THREAD

**Issue by facadev** [RGB-Tools/rgb-sandbox#1]
```
==== installing bdk-cli   ====
installing bdk-cli to bdk-cli
demo.sh: line 95: cargo: command not found

==== starting services    ====
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

...
```

My environment is macOS 13.2.1 (22D68).

**Comment by nicbus** [comment]
looks like the script can't call `cargo`, so it can't install `bdk-cli`

`cargo` is distributed with rust by default, so if you don't have it then you probably need to install the rust programming language, either via your package manager of choice or via [rustup](https://rustup.rs/)
